INSERT INTO exercizer.subject_lesson_level (label) VALUES
('6ème'),
('5ème'),
('4ème'),
('3ème'),
('4ème pro'),
('3ème pro'),
('Seconde'),
('1ère'),
('Terminale'),
('BTS 1ère année'),
('BTS 2nde année'),
('CPGE 1ère année'),
('CPGE 2nde année'),
('CAP 1ère année'),
('CAP 2nde année'),
('BP 1ère année'),
('BP 2nde année'),
('Seconde Pro'),
('1ère Pro'),
('Terminale Pro');

INSERT INTO exercizer.subject_lesson_type (label) VALUES
('Arts appliqués'),
('Arts plastiques'),
('Biotechnologies et ST2S'),
('Documentation (Cdi)'),
('Économie et gestion'),
('Éducation musicale'),
('Éducation physique et sportive'),
('Histoire géographie'),
('Langues vivantes'),
('Lettres et Langues et Culture de l''Antiquité'),
('Mathématiques'),
('Physique chimie'),
('Sciences Économiques et Sociales'),
('Sciences de la vie et de la Terre'),
('Technologie au collège'),
('Enseignement professionnel'),
('Enseignement technologique (STI, STMG, ST2S, STL)'),
('Philosophie'),
('Méthodologie'),
('Enseignement moral et civique '),
('Droit'),
('Autre');

INSERT INTO exercizer.subject_tag (label) VALUES
('Facile'),
('Intermédiaire'),
('Difficile'),
('Entrainement'),
('Devoir maison'),
('Contrôle');