UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.choose' WHERE id=1;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.chooseanswer' WHERE id=2;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.statement' WHERE id=3;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.simpleanswer' WHERE id=4;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.openanswer' WHERE id=5;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.multipleanswers' WHERE id=6;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.qcm' WHERE id=7;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.association' WHERE id=8;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.orderby' WHERE id=9;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.texttofill' WHERE id=10;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.areaselect' WHERE id=11;
UPDATE exercizer.grain_type SET public_name='exercizer.grain.type.areaselectimage' WHERE id=12;

UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level1' WHERE label='6ème';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level2' WHERE label='5ème';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level3' WHERE label='4ème';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level4' WHERE label='3ème';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level5' WHERE label='4ème pro';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level6' WHERE label='3ème pro';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level7' WHERE label='Seconde';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level8' WHERE label='1ère';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level9' WHERE label='Terminale';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level10' WHERE label='BTS 1ère année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level11' WHERE label='BTS 2nde année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level12' WHERE label='CPGE 1ère année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level13' WHERE label='CPGE 2nde année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level14' WHERE label='CAP 1ère année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level15' WHERE label='CAP 2nde année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level16' WHERE label='BP 1ère année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level17' WHERE label='BP 2nde année';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level18' WHERE label='Seconde Pro';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level19' WHERE label='1ère Pro';
UPDATE exercizer.subject_lesson_level SET label='exercizer.subject.lesson.level20' WHERE label='Terminale Pro';

UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type1' WHERE label='Arts appliqués';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type2' WHERE label='Arts plastiques';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type3' WHERE label='Biotechnologies et ST2S';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type4' WHERE label='Documentation (Cdi)';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type5' WHERE label='Économie et gestion';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type6' WHERE label='Éducation musicale';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type7' WHERE label='Éducation physique et sportive';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type8' WHERE label='Histoire géographie';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type9' WHERE label='Langues vivantes';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type10' WHERE label='Lettres et Langues et Culture de l''Antiquité';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type11' WHERE label='Mathématiques';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type12' WHERE label='Physique chimie';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type13' WHERE label='Sciences Économiques et Sociales';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type14' WHERE label='Sciences de la vie et de la Terre';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type15' WHERE label='Technologie au collège';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type16' WHERE label='Enseignement professionnel';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type17' WHERE label='Enseignement technologique (STI, STMG, ST2S, STL)';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type18' WHERE label='Philosophie';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type19' WHERE label='Méthodologie';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type20' WHERE label='Enseignement moral et civique ';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type21' WHERE label='Droit';
UPDATE exercizer.subject_lesson_type SET label='exercizer.subject.lesson.type22' WHERE label='Autre';
