GRANT USAGE ON SCHEMA exercizer TO "ode-app";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA exercizer TO "ode-app";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA exercizer TO "ode-app";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA exercizer TO "ode-app";