GRANT USAGE ON SCHEMA exercizer TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA exercizer TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA exercizer TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA exercizer TO "apps";